# File: .goreleaser.yaml (complete file)
version: 2

project_name: vpn-leak-identifier

builds:
  - id: vpn-leak-identifier
    main: ./cmd/vpn-leak-identifier
    binary: vli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/baptistax/vpn-leak-identifier/internal/version.Version={{ .Version }}
      - -X github.com/baptistax/vpn-leak-identifier/internal/version.Commit={{ .Commit }}
      - -X github.com/baptistax/vpn-leak-identifier/internal/version.BuildDate={{ .Date }}

archives:
  - id: default
    formats: [ 'binary' ]
    name_template: 'vpn-leak-identifier_{{ .Os }}_{{ .Arch }}{{ if eq .Os "windows" }}.exe{{ end }}'

checksum:
  name_template: "checksums.txt"
